title: Blue Comet Labs
url: https://bluecometlabs.com
timezone: Asia/Tokyo

links:
  github: https://github.com/bluecometlabs
  twitter: https://twitter.com/BlueCometLabs
  mastodon: https://mastodon.social/@bluecometlabs
  expenses_site: https://getexpenses.app
  expenses: https://apple.co/42KJ3Rk
  eightplanets_site: https://8planets.app
  eightplanets: https://apple.co/3dGblS6
  rokuyo: https://apple.co/3GAlIDA
  passwordgen: https://apple.co/31Hm9gF
  rerere: https://apple.co/3KQdton
  ondrip: https://apple.co/4dpfE1N

sass:
  style: compressed
strict_front_matter: true

plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-redirect-from

# https://jekyllrb.com/docs/configuration/default/
exclude:
- .github
- .gitignore
- .jekyll-cache
- .sass-cache
- CNAME
- LICENSE
- README.md
